### ISSUE TITLE
Incorrect character count

### ISSUE THREAD

**Issue by WiseGirl** [rhyswynne/inline-tweet-sharer#14]
I discovered that the plugin was incorrectly counting and prematurely cutting off tweets due to HTML encoded characters. For example, a quote may be counted as 6 characters (&quot;)

In order to alleviate the situation, I updated the count like this:

` if ((strlen(utf8_decode($tweetlinkstring))+strlen($permalink)) > 140 ) {
        $tweetlinkstring = substr( $tweetlinkstring, 0, (140-(strlen(utf8_decode($tweetlinkstring))+strlen($permalink)+3)) );
        $tweetlinkstring = preg_replace( '/ [^ ]*$/', '...', $tweetlinkstring );
    }`

This decodes the tweet string for accurate character count, and also accounts for the length of the link.

**Comment by rhyswynne** [comment]
Hi there,

Nice catch!

Could you submit this as a pull request (if known)? I can merge it in and then test it.

I think it may also be better using html_entity_decode, rather than utf8_decode, for those databases that have weird charsets.

Thanks for spotting it!

Rhys

**Comment by WiseGirl** [comment]
Will try! I'm kind of new to this system. Oddly enough, I tried html_entity_decode first and that did not end up with a correct count. I'm not sure why... If I have time later, I'll play around with it.

**Comment by rhyswynne** [comment]
Totally missed this, sorry. I've merged your changes. Please check.
